### ISSUE TITLE
IOT Microchip Ethernet Kit Insight of Things Problem

### ISSUE THREAD

**Issue by chip270** [MicrochipTech/aws-iot-firmware-pic32mz#13]
Currently I'm working on the Microchip Ethernet kit. All I can say was the insight of things application was working. Until I followed the guide on the mediumone which is partnered with microchip website as follows:-

Re-configuring a board for a new project 
A sensor board can be reconfigured to be connected to another project with the following steps: 
Clear a sensor board configuration by pressing and holding down switches S2 and S3, and switching the board power off and on.  Keep holding S2 and S3 depressed while you see green LEDs flashing in a rotating pattern until you see a blue LED D5 turn on. 

Then after this the insight of things application is frozen with the display setting not altering. So the potentiometer settings is frozen at 509 also the buttons pressed S2 and S3 are displaying pressed. I did also reinstall the insight software but it stays at the same settings 509 value even when moving the potentiometer. I have tried installing the embedded software on the board again but the problem is still the same. Has anyone had the same issues and could offer advice.

**Comment by Oakeson** [comment]
Pressing S2 and S3 deleted the certificates on the board, so it can no longer talk to AWS. Insight on Things can talk to AWS, but nothing is changing, so it looks frozen. You need to use Insight on Things to delete the shadow on AWS. If it fails anything during delete, you need to log on to the AWS console, go to the IoT section and manually delete stuff. Then go back to the Insight app and reconnect with your board as if it was brand new. 

Disclaimer: I'm not a developer on this project

**Comment by bellhop** [comment]
@chip270, @Oakeson is correct.  When you reloaded the firmware it does not have any certs loaded.  And, because you create a new set of certs each time you run the setup process you will have to remove the old artifacts that are loaded in AWS first.  

Please see this link on the same issue: https://github.com/MicrochipTech/aws-iot-insight-on-things-desktop-app/issues/8

**Comment by Oakeson** [comment]
@bellhop, is there a way to protect the NVM address space from MPLAB X IDE so that the certs aren't deleted when downloading new or debug FW? In my case, I'm using a PICkit3 and looking at the PICkit3 "Memories to Program" section in the Project Properties. It appears the certs are written to the area with an address just beyond 0x80000000. Thanks!

**Comment by bellhop** [comment]
@Oakeson you could do one of the following.

1. You could add an external EEProm to the board and us it to store the certs.  
2. Read the memory out of the part and save the blocks that have the NVM data, build your new code and then merge these together before you program (you will have to update the checksum value)
3. Modify the Insight on Things desktop app to store the cert and use it to reload all of the NVM info

When we designed this, we wanted to show customers what it would be like to have a one to one cert that would not be stored outside of the NVM as this is how one could go to production.

**Comment by bellhop** [comment]
Closing this issue as we have not heard any feedback and issue should be solved per above instructions.
